name: Infra Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths:
      - "Infrastructure/**"

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      env: dev
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Deploy Bicep to Azure
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: dp-github-tradingking
          location: koreacentral
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./Infrastructure/main.bicep
          parameters: >
              {
                "env": ${{ env.env }},
                "location": "koreacentral",
                "serverNumber": "01",
                "issKey": ${{ secrets.ISS_KEY }},
                "registryUrl": "tradingking.azurecr.io/tradingking${{ env.env }}:latest",
                "registryUserName": "tradingking",
                "registryPassword": ${{ secrets.ACR_PASSWORD }}
              }
